# Generated by Django 5.2.5 on 2025-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diab_medications', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationorder',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddIndex(
            model_name='medicationorder',
            index=models.Index(fields=['patient', 'start_date'], name='diab_medica_patient_51171f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationorder',
            index=models.Index(fields=['drug_name', 'start_date'], name='diab_medica_drug_na_3a75fd_idx'),
        ),
    ]
