# Generated by Django 4.2.11 on 2025-09-02 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=48)),
                ('resource_id', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('diff', models.JSONField(blank=True, null=True)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'record_versions',
                'ordering': ['-version'],
                'unique_together': {('resource_type', 'resource_id', 'version')},
            },
        ),
    ]
