# Generated by Django 5.2.5 on 2025-09-01 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=120)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('reference_range', models.CharField(blank=True, max_length=50)),
                ('taken_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients_core.patient')),
            ],
        ),
    ]
