# Generated by Django 5.2.5 on 2025-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diab_labs', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient', 'taken_at'], name='diab_labs_l_patient_1470a3_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['test_name', 'taken_at'], name='diab_labs_l_test_na_9b4b35_idx'),
        ),
    ]
