# Generated by Django 4.2.11 on 2025-09-02 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=32)),
                ('resource_id', models.UUIDField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='patients_core.patient')),
            ],
            options={
                'db_table': 'ai_summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='ai_summarie_patient_10f9db_idx'), models.Index(fields=['resource_type', 'resource_id'], name='ai_summarie_resourc_74c026_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aisummary',
            constraint=models.UniqueConstraint(fields=('resource_type', 'resource_id'), name='unique_summary_per_resource'),
        ),
    ]
