# Generated by Django 4.2.11 on 2025-09-02 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinical_references',
                'ordering': ['topic', 'title'],
                'indexes': [models.Index(fields=['topic'], name='clinical_re_topic_ab28b0_idx'), models.Index(fields=['source'], name='clinical_re_source_ff9270_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clinicalreference',
            constraint=models.UniqueConstraint(fields=('title', 'source'), name='uniq_ref_title_source'),
        ),
    ]
