# Generated by Django 4.2.11 on 2025-09-02 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_code', models.CharField(blank=True, max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('reference_range', models.CharField(blank=True, max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients_core.patient')),
            ],
            options={
                'db_table': 'lab_results',
                'ordering': ['-taken_at'],
            },
        ),
    ]
