# Generated by Django 4.2.11 on 2025-09-02 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.JSONField(blank=True, default=dict)),
                ('assessment', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients_core.patient')),
            ],
            options={
                'db_table': 'encounters',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['patient', '-occurred_at'], name='encounters_patient_01cd92_idx')],
            },
        ),
    ]
