# Generated by Django 5.2.5 on 2025-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diab_encounters', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'occurred_at'], name='diab_encoun_patient_0dac9d_idx'),
        ),
    ]
